name: Download Stockfish
on: workflow_dispatch

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Stockfish Engine
        run: |
          wget https://github.com/official-stockfish/Stockfish/releases/download/sf_18/stockfish-windows-x86-64-avx2.zip
          
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stockfish-windows-x86-64-avx2.zip
          git commit -m "Add Stockfish binary"
          git push
